### ISSUE TITLE
All episodes call returns first 10 episodes only

### ISSUE THREAD

**Issue by yoKurt94** [Danoctum/South-Park-API#13]
Is there a way to get all episodes from all seasons or at least all episodes from one season with one request? When using
`https://spapi.dev/api/episodes/`
the server only returns the first 10 elements. I would like to work with your API but it would be nice if there was a way to get more episodes at once.

**Comment by Danoctum** [comment]
Thanks for your issue, the API uses pagination to reduce request size and server load. I'm not planning on adding an endpoint that returns all episodes, since it's possible to retrieve all episodes by using the pagination.

**Comment by yoKurt94** [comment]
Okay, is it correct that `https://spapi.dev/api/episodes/` always returns episode 1-10  (which is season 1 and some episodes of season 2 I guess) and there is no way to get all episodes of a single season at once?

**Comment by Danoctum** [comment]
Per season is not possible, and I'm not looking to add that for now. If you want add features (that make the API more convenient for you) to the code, feel free to fork and adjust the API to your needs 😄
