### ISSUE TITLE
Search Parameter is not working properly

### ISSUE THREAD

**Issue by ghlps** [Danoctum/South-Park-API#14]
I'm receiving the error 500 when trying to access `https://spapi.dev/api/characters?search=eric`.

When I try to use `https://spapi.dev/api/episodes?search=eric` everything looks fine.

**Comment by sylvainp** [comment]
Yes, I have the same error

**Comment by Danoctum** [comment]
Thanks for reporting the issue, I've fixed the issue and will deploy it shortly!
